### ISSUE TITLE
Support "first" and "last" attribute for conditions

### ISSUE THREAD

**Issue by sebastiankliem** [frederike-ramin/gamification#47]
Example: Badge "Be the first who submits a homework"

How can this be configured in the YAML?

**Comment by corinnaj** [comment]
I think we can do this by giving the badge only once in the scope of a course. The next time a `SubmittedHomework` event is triggered for the same courses, maxAwarded (which is implicitly 1) has already been reached.

**Comment by cmfcmf** [comment]
Closing this, because @corinnaj explained how it can be done. Feel free to reopen this if you have further questions.
